version: '3.9'

services:
  db:
    image: postgres
    container_name: ticketing-user-db
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ticketing-user-db
